// Generated by RANE C backend (bootstrap)
#include <stdint.h>
#include <stddef.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>

#include "rane_rt.h"

static uint64_t main(void);

static uint64_t main(void) {
  uint64_t r[256] = {0};
  uint64_t s[1] = {0};
  uint64_t call_arg_bytes = 0;
  uint64_t* call_stack = NULL;
  size_t call_stack_words = 0;
  if (call_stack) free(call_stack);
  return r[0];
  if (call_stack) free(call_stack);
  return r[0];
}

int main(int argc, char** argv) { (void)argc; (void)argv; (void)main(); return 0; }
